name: Unit Test CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  ci-test:
    runs-on: tzrec-runner
    container:
      image: mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/easyrec/tzrec-devel:0.6
      options: --gpus all --ipc host
    env:
      WORK_DIR: /__w/work_${{ github.run_id }}
    steps:
      - name: Create a new work directory
        run: mkdir -p ${{ env.WORK_DIR }}
      - name: FetchCommit ${{ github.event.pull_request.head.sha }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ env.WORK_DIR }}
      - name: RunUnitTestCI
        id: run_unittest_ci
        run: |
          cd ${{ env.WORK_DIR }}
          bash scripts/ci_test.sh
